title: Li-Ting's GitHub
logo: https://drive.google.com/file/d/18Z7Qxlv6Dy7v8boIEloMy5tPfvORUHcC/view?usp=sharing
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
